#GİRİLEN BİR SAYININ 0 100 ARASINDA OLUP OLMADIĞINI KONTROL EDİNİZ 

x=int(input("Bir sayi giriniz de 0 100 arasinda olup olmadiğina bir bakalim: "))
if x>0 and x<100:
    print("Sayi 0 ve 100 arasindadir.")
else:
    print("Sayi 0 ve 100 arasinda degildir. ")


#BU ÖRNEKLERDE BİR ŞEY YOK YA ZAMAN KAYBETMEYE GEREK YOK BENCE
#ORNEKLER VUCUT KITLE ENDEKSI,FİNAL NOTUNA GORE SINIFLANDIRMA AMA BİR KAC FARKLI KOSUL İLE SADECE,GIRILEN 3 SAYININ KENDİ ARALARINDA KIYASLANMALARI VESAİRE

#KITLE ENDEKSİNDE SINIFLANDIRMALAR MEVCUT 